config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :users do
    post 'redirect_users', on: :member
    post 'redirect_users', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :gender, presence: true
  validates :birthday, presence: true

  scope :name_like, ->(name) { where('name like ?', "%#{name}%") if name.present? }
  scope :gender_is, ->(gender) { where(gender: gender) if gender.present? }
  scope :birthday_is, ->(birthday) { where(birthday: birthday) if birthday.present? }
  scope :prefecture_id_is, ->(prefecture_id) { where(prefecture_id: prefecture_id) if prefecture_id.present? }
  scope :search, ->(search_form) {
    name_like(search_form.name)
      .gender_is(search_form.gender)
      .birthday_is(search_form.birthday)
      .prefecture_id_is(search_form.prefecture_id)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def keep_last_pagination_data
    session[:last_pagination_data] = { params:     request.query_parameters,
                                       controller: controller_name,
                                       action:     action_name }
  end

  def discard_last_pagination_data
    session[:last_pagination_data] = nil
  end

  def load_pagination_params(action)
    ret = {}
    if (data = session[:last_pagination_data])
      if data["controller"] == controller_name && data["action"] == action.to_s
        ret = data["params"]
      end
    end
    discard_last_pagination_data
    ret
  end

  def redirect_with_kept_pagination_params(action:, **args)
    redirect_to({ action: action, params: load_pagination_params(action) }, args)
  end
end

app/controllers/concerns/redirect_action.rb
module RedirectAction
  extend ActiveSupport::Concern

  def redirect_users
    redirect_with_kept_pagination_params(action: :index, notice: 'redirect_users_action is done!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include RedirectAction
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  after_action :keep_last_pagination_data, only: [:index]

  # GET /users
  # GET /users.json
  def index
    @user_search_form = UserSearchForm.new(user_search_params)
    @users = User.search(@user_search_form).page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :gender, :birthday, :prefecture_id, :profile)
  end

  def user_search_params
    params.fetch(:user_search_form, {}).permit(:name,
                                               :gender,
                                               :birthday,
                                               :prefecture_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KaminariSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :prefecture_id %>
    <%= form.number_field :prefecture_id %>
  </div>

  <div class="field">
    <%= form.label :profile %>
    <%= form.text_area :profile %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= form_with(model: @user_search_form, url: users_path, method: :get, local: true) do |form| %>
  <div class="field">
<!--    # TODO text_fieldからラジオボタンとかリストにする-->
<!--    # TODO Viewを部品化する-->
<!--    # WANT prefecture_ids select2で実装すると空文字が入るのでフォームオブジェクトでいい感じに対応する-->
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :gender %>
    <%= form.text_field :gender %>
    <%= form.label :birthday %>
    <%= form.date_field :birthday %>
    <%= form.label :prefecture_id %>
    <%= form.text_field :prefecture_id %>
  </div>
  <div class="actions">
    <%= form.submit("検索") %>
  </div>
<% end %>

<%= paginate @users %>
<%= page_entries_info @users %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Birthday</th>
      <th>Prefecture</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.gender %></td>
        <td><%= user.birthday %></td>
        <td><%= user.prefecture_id %></td>
        <td><%= user.profile %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'RedirectUsers', redirect_users_users_path, method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @user.prefecture_id %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @user.profile %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'RedirectUsers', redirect_users_user_path(@user), method: :post %>